# Generated by scripts/brew-formula.sh in discobox-ai/discobox. Do not edit by hand.
class DiscoboxDev < Formula
  desc "Sandboxed development environments for coding agents (latest channel)"
  homepage "https://github.com/discobox-ai/discobox"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    # Apple Silicon only. ADR 0062 defers Intel Macs and assemble-guest-image
    # refuses non-arm64, so an Intel binary would install and then fail at the
    # first pool.
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.8.1/discobox-darwin-arm64"
      sha256 "2a463e01d55abbfc24a30d7d584438b067d50e4f8f1b8108fb17bd4b13dfa72e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.8.1/discobox-linux-amd64"
      sha256 "a3cfb6f4a6096dae8687137caf857ae305192a78ecf98da439cff861c9cb989b"
    end
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.8.1/discobox-linux-arm64"
      sha256 "c04cf032e209a57b2623daa51675e64654e8bd027ceea62631bbc89971234d70"
    end
  end

  def install
    bin.install Dir["discobox-*"].first => "discobox-dev"
  end

  def caveats
    <<~EOS
      This is the latest channel: it tracks the newest tagged release, which
      has not been marked stable. Install it beside "discobox" and run it as
      "discobox-dev".

      Both share one state directory, one configuration, and one server stage,
      so their servers cannot run at the same time — that is deliberate, and
      whichever you start second will say so. Stop one before starting the
      other.

      This installs the client. The Discobox server is a separate program,
      downloaded on demand the first time something needs one locally and kept
      under your state directory by version. It is checked against the SHA-256
      this release was cut with, which is carried inside this binary; run
      "discobox-dev admin server stage" to fetch it in advance, or
      "discobox-dev admin server manifest" to see exactly what it would fetch.
    EOS
  end

  test do
    # Proves both that the binary runs on the platform it was installed for —
    # what a cross-compiled release most plausibly gets wrong — and that it is
    # the version this formula claims.
    assert_match version.to_s, shell_output("#{bin}/discobox-dev --version")
  end
end
