# Generated by scripts/brew-formula.sh in discobox-ai/discobox. Do not edit by hand.
class Discobox < Formula
  desc "Sandboxed development environments for coding agents"
  homepage "https://github.com/discobox-ai/discobox"
  version "0.1.0-alpha.10"
  license "Apache-2.0"

  on_macos do
    # Apple Silicon only. ADR 0062 defers Intel Macs and assemble-guest-image
    # refuses non-arm64, so an Intel binary would install and then fail at the
    # first pool.
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.1.0-alpha.10/discobox-darwin-arm64"
      sha256 "a6c57eba6c388c86dd7a244e1ded66c6bb9e3c3e3cb0c3ac25584ceed34f51de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.1.0-alpha.10/discobox-linux-amd64"
      sha256 "5785e8553d4914ff6c03b2effd0d405b0fa9f6583fda2328ae8f20b4c13212e4"
    end
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.1.0-alpha.10/discobox-linux-arm64"
      sha256 "f411ac15d5a3f92f85f12a0c7f4ed2eb4bcf08ad355ff2079ace3f59a838064a"
    end
  end

  def install
    bin.install Dir["discobox-*"].first => "discobox"
  end

  def caveats
    on_macos do
      <<~EOS
        This binary is ad-hoc signed with com.apple.security.virtualization,
        which Virtualization.framework requires to create a VM. Without it a
        macOS pool cannot start.

        com.apple.vm.networking is deliberately absent. It is what puts guests
        on your LAN, and Apple grants it by request; pool guests are NAT'd by
        the framework instead.
      EOS
    end
  end

  test do
    # Proves both that the binary runs on the platform it was installed for —
    # what a cross-compiled release most plausibly gets wrong — and that it is
    # the version this formula claims.
    assert_match version.to_s, shell_output("#{bin}/discobox --version")
  end
end
