# Generated by scripts/brew-formula.sh in discobox-ai/discobox. Do not edit by hand.
class Discobox < Formula
  desc "Sandboxed development environments for coding agents"
  homepage "https://github.com/discobox-ai/discobox"
  version "0.1.0-alpha.15"
  license "Apache-2.0"

  on_macos do
    # Apple Silicon only. ADR 0062 defers Intel Macs and assemble-guest-image
    # refuses non-arm64, so an Intel binary would install and then fail at the
    # first pool.
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.1.0-alpha.15/discobox-darwin-arm64"
      sha256 "a58d03bdb6c318e16aee6526930803cd94fddefac2d0012579cde85bf2ab6ce4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.1.0-alpha.15/discobox-linux-amd64"
      sha256 "2107b9519a57a31eea3574db4e9ecdbbfa9ecf96417284913cff13483c7554e2"
    end
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.1.0-alpha.15/discobox-linux-arm64"
      sha256 "f4859d2249690fbb61c806f9ede988e9268ca27925c15c4c042038166fcaeaf7"
    end
  end

  def install
    bin.install Dir["discobox-*"].first => "discobox"
  end

  def caveats
    on_macos do
      <<~EOS
        This binary is ad-hoc signed with com.apple.security.virtualization,
        which Virtualization.framework requires to create a VM. Without it a
        macOS pool cannot start.

        com.apple.vm.networking is deliberately absent. It is what puts guests
        on your LAN, and Apple grants it by request; pool guests are NAT'd by
        the framework instead.
      EOS
    end
  end

  test do
    # Proves both that the binary runs on the platform it was installed for —
    # what a cross-compiled release most plausibly gets wrong — and that it is
    # the version this formula claims.
    assert_match version.to_s, shell_output("#{bin}/discobox --version")
  end
end
