# Generated by scripts/brew-formula.sh in discobox-ai/discobox. Do not edit by hand.
class Discobox < Formula
  desc "Sandboxed development environments for coding agents"
  homepage "https://github.com/discobox-ai/discobox"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    # Apple Silicon only. ADR 0062 defers Intel Macs and assemble-guest-image
    # refuses non-arm64, so an Intel binary would install and then fail at the
    # first pool.
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.2.0/discobox-darwin-arm64"
      sha256 "80e984d42e28caceb57031746d0a81d5550e89b43d485a64ff54edb91fcc5600"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.2.0/discobox-linux-amd64"
      sha256 "4f2c9ad40d982c9dd55e17b0d4f21257a8a442d19c709df1069ae7c5761a0093"
    end
    on_arm do
      url "https://github.com/discobox-ai/discobox/releases/download/v0.2.0/discobox-linux-arm64"
      sha256 "defbab1138101cbbdd8d5b9c1dae3a99e7a0cddf05b71e8d5d8fe714b73b7f26"
    end
  end

  def install
    bin.install Dir["discobox-*"].first => "discobox"
  end

  def caveats
    on_macos do
      <<~EOS
        This binary is ad-hoc signed with com.apple.security.virtualization,
        which Virtualization.framework requires to create a VM. Without it a
        macOS pool cannot start.

        com.apple.vm.networking is deliberately absent. It is what puts guests
        on your LAN, and Apple grants it by request; pool guests are NAT'd by
        the framework instead.
      EOS
    end
  end

  test do
    # Proves both that the binary runs on the platform it was installed for —
    # what a cross-compiled release most plausibly gets wrong — and that it is
    # the version this formula claims.
    assert_match version.to_s, shell_output("#{bin}/discobox --version")
  end
end
